_target_: src.data.module.DataModule

hparams:
  dataset: MD22
  dataset_slug: md22
  label:
  dataset_root: ${paths.data_dir}/md22 # data_path is specified in config.yaml
  derivative: true
  split_mode: null
  reload: 0
  batch_size: 8
  inference_batch_size: 32
  standardize: true
  splits: null
  train_size: 950
  val_size: 50
  test_size: null
  num_workers: 12
  seed: 1
  output_dir: ${paths.output_dir}
  ngpus: 1
  num_nodes: 1
  precision: 32
  task: train
  distributed_backend: ddp
  redirect: false
  accelerator: gpu
  test_interval: 1500
  save_interval: 1
  prior_model: null
  normalize_positions: false
